[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "C21vgVwS2X1g9XmSyJPFtLfrob5zwwoij54L7Rq6dmes"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
